### ISSUE TITLE
Unable to connect to backup engine, retry?

### ISSUE THREAD

**Issue by rubylaser** [JrCs/docker-crashplan#1]
Thanks for this, but I'm hitting a snag. I'm on Ubuntu 14.04.3 Server, and I'm trying to get this working.  I set it up like this (a little different than your directions).

```
  docker run -d \
  --name crashplan \
  -h $HOSTNAME \
  -e TZ \
  --publish 4242:4242 --publish 4243:4243 \
  --volume /config/crashplan:/var/crashplan \
  --volume /storage:/storage \
  jrcs/crashplan:latest
```

The directories are all chmod'd to 777, and the sub folders are all created.  

```
root@fileserver:~# ls /config/crashplan/
bin  cache  conf  id  lang  lib  log
```

I copied the .ui_info string over to my Mac, but when I try to connect, I just see a message that it can't connect to the backup engine.  I'm ssh'd the ports like this.

```
ssh -L 4243:localhost:4243 root@192.168.172.10
```

Any ideas to get this working properly?  Thanks!

**Comment by JrCs** [comment]
Is a telnet on localhost:4243 or a telnet on the host:4243 return something ?

**Comment by rubylaser** [comment]
Here's telnet on the Ubuntu server to those two ports.

```
root@fileserver:~# telnet localhost 4243
Trying ::1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
root@fileserver:~# telnet localhost 4242
Trying ::1...
Connected to localhost.
Escape character is '^]'.
�cA-18782|com.code42.messaging.security.SecurityProviderReadyMessage��"S���4aKrm9�
9����
C��]�M���8^]
```

Here's from my Mac to the server (this does not work).  

```
macbook-air:~ rubylaser$ telnet 192.18.172.10 4242
Trying 192.18.172.10...
# Just sits here forever

macbook-air:~ rubylaser$ telnet 192.18.172.10 4243
Trying 192.18.172.10...
# Just sits here forever
```

There is no firewall enabled on my Mac and the  iptables -L entries on the host appear to be in place.

```
root@fileserver:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:tproxy
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:8443
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:8843
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:8880
ACCEPT     tcp  --  anywhere             172.17.0.9           tcp dpt:4242
ACCEPT     tcp  --  anywhere             172.17.0.9           tcp dpt:4243
```

**Comment by JrCs** [comment]
So the problem is with 192.18.172.10.
If it a virtual machine perhaps it's a problem with is configuration ?
In any case the problem is not from the container but access to the container from external client.

**Comment by rubylaser** [comment]
The Docker host is a physical Ubuntu 14.04.3 server.  I'm just not sure why this container isn't accessible from my Mac, but others are.  I guess more research is in order for me :)

**Comment by rubylaser** [comment]
As @JrCs, this was definitely a problem with my Mac and not this container.  I did get this working, by changing the .ui_info on my Mac to point to port 4200 and then port forwarding via ssh to 4200 rather than the default 4243.  I'm not sure why this worked and using the default port didn't, but I'm just glad it's working now :)

```
ssh -L 4200:localhost:4243 root@fileserver
```

**Comment by JrCs** [comment]
Perhaps 4243 is already used by crashplan on your mac ?

**Comment by rubylaser** [comment]
It typically is, but I had already stopped the process via launchctl like this.

```
sudo launchctl unload /Library/LaunchDaemons/com.crashplan.engine.plist
```
