### ISSUE TITLE
[Question] Best performance settings?

### ISSUE THREAD

**Issue by blankster** [JrCs/docker-crashplan#10]
As we all know Crashplan has sometimes at least very slow upload speeds. As I've got a 1 Gbit connection I'm very interested todo what ever helps to improve upload speeds.

Via client I was able to set the following:
![image](https://cloud.githubusercontent.com/assets/1443109/15321165/109028ee-1c35-11e6-9634-3b7dc948fc5e.png)

I'm getting 4 to 6 Mbit/s with this settings what is better than the usual 2-3 Mbit/s (!= Megabyte) - with big files. Are there other possible settings to improve this further? I'm using 2 GB RAM and the CPU isn't extremely used (below 30% most times). Any ideas?

**Comment by JrCs** [comment]
Sorry but i don't have any hints about crashplan application.
Try to post your request on the crashplan or synology forum.
