### ISSUE TITLE
trouble compiling/installing manually

### ISSUE THREAD

**Issue by WS-Dave** [JrCs/docker-crashplan#11]
Synology 1515+ running DSM 6.0-7321 Update 7

I'm new to Docker (but not to crashplan) and I'm trying to manually install (so I could review the source code before committing this code/approach to being part of my backup system).  

I'm doing the following:
wget https://github.com/JrCs/docker-crashplan/archive/master.zip
7z x master.zip
cd docker-crashplan-master/

I have tried running the build.sh script as well as manually running 
docker build -t jrcs/crashplan .
and
docker build -t jrcs/crashplan:latest .

In all cases, the build does most parts but fails shortly after downloading jre with the errors
"
sed: can't read /usr/local/crashplan/conf/default.service.xml: No such file or directory
The command '/bin/sh -c chmod +x /tmp/installation/install.sh && sync && /tmp/installation/install.sh && rm -rf /tmp/installation' returned a non-zero code: 2
"

thoughts on what is failing?

thx!
-Dave

**Comment by JrCs** [comment]
No i really don't know. But why are you wanted to recreate a new image instead of using that are in docker-hub ?

**Comment by WS-Dave** [comment]
the two reasons for compiling manually
1) to use it as an opportunity to better understand how Docker packages work

2) In no way as an offense to you - I am a bit nervous about using the image straight from docker-hub because I can't tell exactly what is in it.  Given the nature of crashplan - whatever solution I use will have access to all of my data as it pushes it to the crashplan cloud.  historically, I have always manually installed the Crashplan....tgz file and all dependencies (java, etc) - so I could verify that all parts of the system were signed/real versions.  but as we know, Synology wipes out these manual installs on every DSM upgrade... so I am looking at Docker and didn't want to start from scratch (esp given the popularity of your system).

**Comment by JrCs** [comment]
I have update to CrashPlan 4.7.0 try to recreate your image. Image creation work out of the box here.
