### ISSUE TITLE
Crashplan continuously upgrading

### ISSUE THREAD

**Issue by mtzro2003** [JrCs/docker-crashplan#12]
Hello Yves!

First, one big thank you for this container!
Second, mine seems that want to upgrade all the time:

I 05/20/16 08:13AM CrashPlan started, version 4.6.0, GUID 719588200052335860
I 05/20/16 08:13AM Installing upgrade - version 1435813200470
I 05/20/16 08:13AM Upgrade installed - version 1435813200470
I 05/20/16 08:13AM CrashPlan started, version 4.7.0, GUID 719588200052335860
I 05/20/16 08:13AM [NAS Backup] Scanning for files to back up
I 05/20/16 08:13AM Backup scheduled to always run
I 05/20/16 08:15AM [NAS Backup] Scanning for files completed in 1 minute: 109,075 files (367.50GB) $
I 05/20/16 08:51AM CrashPlan started, version 4.6.0, GUID 719588200052335860
I 05/20/16 08:51AM Installing upgrade - version 1435813200470
I 05/20/16 08:51AM Upgrade installed - version 1435813200470
 05/20/16 08:52AM CrashPlan started, version 4.7.0, GUID 719588200052335860
I 05/20/16 11:53AM CrashPlan started, version 4.6.0, GUID 719588200052335860
I 05/20/16 11:53AM Backup scheduled to always run
I 05/20/16 11:53AM Downloading a new version of CrashPlan.
W 05/20/16 11:53AM Unable to apply upgrade(s), retrying in one hour
I 05/20/16 12:00PM Downloading a new version of CrashPlan.
I 05/20/16 12:01PM Download of upgrade complete - version 1435813200470.
I 05/20/16 12:01PM CrashPlan has downloaded an update and will restart momentarily to apply the upd$
I 05/20/16 12:01PM Installing upgrade - version 1435813200470

Do you have any idea what's wrong?

**Comment by mtzro2003** [comment]
May be something with the environment?
CRASHPLAN_VERSION   4.6.0

**Comment by JrCs** [comment]
Crashplan have made a big update (4.7.0) and i need to check why the upgrade failed.

**Comment by JrCs** [comment]
Docker container update with CrashPlan 4.7.0.
