### ISSUE TITLE
Memory setting is not persistent since 4.7

### ISSUE THREAD

**Issue by Kyosfonica** [JrCs/docker-crashplan#13]
It seems that Crashplan has changed the way to set more ram to the JVM. My current memory setting in the run.cfg is no longer working since the update. 
There is a workaroud to manually set it through the Crasplan client using the "java mx 'value' restart" command.
The problem is that this workaround is not persistent after a restart of the Docker container.

**Comment by JrCs** [comment]
We need to find some documentation from crashplan how to change correctly this parameters

**Comment by JrCs** [comment]
@Kyosfonica no more documentation about to change the JVM parameter ?

**Comment by Kyosfonica** [comment]
I was unable to find more info in the subject. I tried contacting CrashPlan but they didn't provide me more info that to modify the ram in the console of the client if the file is not read. I will keep trying to get more info though.

**Comment by JrCs** [comment]
@Kyosfonica can you test the `dev` version ?

**Comment by Kyosfonica** [comment]
It seems that it did not change anything.
Using the dev build reports the 1024m setting ignoring the 9216m that I have set in the run.cfg file.
![image](https://cloud.githubusercontent.com/assets/5280026/20466533/66c85d52-af75-11e6-8f42-c8d03f535284.png)

**Comment by Kyosfonica** [comment]
I had an issue yesterday and my server got down. Today when I started all the services again I gladly saw that Crashplan kept the java memory configuration I set after the first start of the machine. So it seems that at first it won't read the file but after you set that in the crashplan client it remembers it.

**Comment by mountaindude** [comment]
@Kyosfonica But the memory configuration stays intact between restarts, as longs CrashPlan doesn't update itself to a new version - then the config files are overwritten. 
At least that is the behaviour I have seen in my system...

**Comment by Kyosfonica** [comment]
On my configuration every restart of the crashplan server required to configure the memory again via the client console. At least now I do not need to do that.

**Comment by JrCs** [comment]
It must work now with the latest docker image.
