### ISSUE TITLE
Abnormally large "@docker" folder from CrashPlan's perspective

### ISSUE THREAD

**Issue by jake-b** [JrCs/docker-crashplan#14]
Hi.  I'm successfully running CrashPlan within Docker on my Synology DS916+.  Thanks for your efforts.

I'm having one issue.  I've mapped my volume so that the container can backup the entire volume using the following parameters:

```
docker run -d \
  --name CrashPlan \
  -h $HOSTNAME \
  -e TZ \
  --publish 4242:4242 --publish 4243:4243 \
  --volume /volume1/crashplan/data:/var/crashplan \
  --volume /volume1/crashplan/storage:/storage \
  --volume /volume1/:/volume1 \
  jrcs/crashplan:latest
```

For some odd reason, CrashPlan sees the /volume1/@docker folder as ~140TB, which is far more than the capacity of my hard drives.

![crashplan](https://cloud.githubusercontent.com/assets/1012393/15730385/43cd4bea-283a-11e6-9423-62805488622d.jpg)

My guess is that there are some hard or soft links that are causing some weird recursive loop, but I'm not sure.  I can manually exclude the docker folder, but I'd rather just point CrashPlan at the full volume.

Any help is appreciated.

**Comment by JrCs** [comment]
What is the docker folder ?
If it is the /var/lib/docker directory you must exclude from your backup.
