### ISSUE TITLE
Problem with device not ready for computer to computer backup

### ISSUE THREAD

**Issue by copperlab** [JrCs/docker-crashplan#17]
I am having a problem where backing up to crashplan cloud works.  But I can't backup from two computers on the same account that are in different locations.  Its an infinite waiting for connection and in logs the backup location is not accessible.  Any help would be appreciated.

**Comment by johnny2678** [comment]
Just set this up and running into the same thing.  It's likely because the internal (LAN) ip being reported is a docker ip that can't be reached from other clients on the LAN.  Haven't found a work-around yet...

**Comment by JrCs** [comment]
You can use the variables `PUBLIC_IP` and `PUBLIC_PORT`to force the ip and port that will be used to access the container from Internet/WAN.

**Comment by johnny2678** [comment]
Right, but what about from the LAN? Right now the internal address shown is
a docker ip not reachable from other clients.

**Comment by JrCs** [comment]
Other clients can use the internet IP to access it

**Comment by JrCs** [comment]
Or you can start your docker container with the `--net=host` option.

**Comment by johnny2678** [comment]
adding `--net=host` instead of publishing ports worked for me. Thanks.

**Comment by MarkJonas** [comment]
What are other side effects of using `--net=host` instead of `--publish 4242:4242 --publish 4243:4243`?

**Comment by MarkJonas** [comment]
After sleeping over this I realized that the LAN connection problem can be solved by adding a route into the router which connects the clients with the Docker server.

`Client <--> Router <--> Server [Docker (CrashPlan)]`

In my home the router (ADSL modem + router) creates a local subnet 192.168.74.0/8. The Docker server has the IP 192.168.74.23. The Docker bridge creates the subnet 172.17.0.0/16. So the router needs to know that to be able to route the traffic to the Docker server which is the gateway for the Docker bridge subnet. Thus, I added a route into the router:

```
Network: 172.17.0.0
Netmask: 255.255.0.0
Gateway: 192.168.74.23
```

Now it is working just fine without having to use `--net=host` (where I still do not know what the side effects are).

These are the network connections the client establishes:

```
$ sudo netstat -nat | grep :42
tcp6       0      0 127.0.0.1:4243          :::*                    LISTEN      1722/java       
tcp6       0      0 192.168.74.90:38368     172.17.0.2:4242         ESTABLISHED 1722/java       
tcp6       0      0 127.0.0.1:40614         127.0.0.1:4243          ESTABLISHED 5733/java       
tcp6       0      0 127.0.0.1:4243          127.0.0.1:40614         ESTABLISHED 1722/java       
tcp6       0      0 192.168.74.90:46168     192.168.74.23:4243      ESTABLISHED 5824/java       
```

**Comment by johnny2678** [comment]
Interesting... the docker engine is supposed to handle the routing to docker networks automatically.

As far as `--net=host`, this allows the docker container to use the full host network (every port).  Almost like the service(s) inside the container were running natively on the host.  It's a bit more risky if you don't know what the container is/should be sending/receiving.
 
Best practices are to specify which ports a container needs, which also has the bonus side effect of being able to remap popular client services (ports 80, 443, etc) through different ports on the host using `-p` or `--publish 8080:80`

When I couldn't get crashplan to work by publishing ports 4242 and 4243, I took the lazy way and tried `--net=host` and it worked.  I should probably be looking through the logs to see if there is a failure on a different port but I just don't have the time right now.

Also curious is I've been running crashplan in this container for nearly 6 month using the `--publish` options and NOT `--net=host`.  Then about a week ago, Code 42 sends me an email that my server isn't backing up.  After checking the logs, i wasn't making a connection to central.crashplan.com for some reason.  Using `--net=host` is a temporary fix until I have time to troubleshoot.

**Comment by noaho** [comment]
> Interesting... the docker engine is supposed to handle the routing to docker networks automatically.

Well.. it does, and that's why MarkJonas's solution works...

When you think about it, the other crashplan clients don't know how to reach 172.*..  they don't have an interface on that network.. so they send all traffic for which they don't know to the 'default gateway'.. and then it is the responsibility of the router to know where to send it next.. that is how tcp/ip routing works.

**Comment by johnny2678** [comment]
My point was, the docker engine adds those routes automatically.  I just checked my routing table and there was already a route to the docker network 172.17.0.0 and I didn't have to add it manually:

```
me@xxx01:~ $ route -v
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         xxx.xxx.xxx.1     0.0.0.0         UG    0      0        0 bond0
172.17.0.0      *         255.255.0.0     U     0      0        0 docker0
xxx.xxx.xxx.0    *         255.255.255.0   U     0      0        0 bond0
```

And the crashplan clients are told how to reach the docker container in part from the client `.ui_info` file where you specify the docker host and exposed port.  From there, the host routing table takes over and routes to the docker network gateway, which routes to the container.

I guess my understanding could be off, but I'm running plenty of other container services with exposed ports on various docker networks and never had to mess with the host routing table.

**Comment by noaho** [comment]
> My point was, the docker engine adds those routes automatically. I just checked my routing table and there was already a route to the docker network 172.17.0.0 and I didn't have to add it manually:

Yes, but did you check the routing table of your other hosts on the network? Not just your docker host. 

The ui.info file is only used to tell the crashplan UI how to connect to the service.. It doesn't have any bearing on the backup engine.. So the backup engine still has the dilemma of having a packet for 172.17 network. Where does it send it? Because your clients only have an interface on 192.168, they decide to send it to your default gateway..
