### ISSUE TITLE
Hibernation synology

### ISSUE THREAD

**Issue by last-Programmer** [JrCs/docker-crashplan#18]
Hi,

When i run this in synology the system is not hibernating. Is there anyway to make the hibernation work?

**Comment by JrCs** [comment]
Sorry i don't know synology. But crashplan always try to connect to main crashplan site. So perhaps it's the reason that your synology doesn't hibernate.
You need to choose between backup and hibernation.
You can also stop crashplan container so that your synology can go to sleep.

**Comment by JrCs** [comment]
No more information.
Closing this issue.
