### ISSUE TITLE
Crashplan Pro container or support?

### ISSUE THREAD

**Issue by fredboyle** [JrCs/docker-crashplan#22]
Would it be possible for you to create, if one doesn't already exist, a container that supports Crashplan Pro?

**Comment by JrCs** [comment]
I don't know how to install CrashPlan Pro.
Are some other user have already succeed with installing CrashPlan Pro in that container ?
If yes, can you open a PR ?

**Comment by amalagaura** [comment]
I used this repo to install Crashplan Pro. I rebuilt the docker image locally after changing the environment variable in the Dockerfile. Then I start that image and it works great.

**Comment by vertigo235** [comment]
Can you just do -E CRASHPLAN_SERVICE=PRO ?

**Comment by amalagaura** [comment]
You are right. I don't know how I missed that. It is just a runtime env var not a build time one

**Comment by vertigo235** [comment]
OK so I take it back, I couldn't get it to work as I described?  I had to modify the docker file as well, but I was able to get the Pro version going with my own image build. @jstewart , it looks like you added the PRO option, how is it supposed to be used?

**Comment by jstewart** [comment]
@vertigo235 - set the $CRASHPLAN_SERVICE environment variable to "PRO" when building the docker image:

```
diff --git a/Dockerfile b/Dockerfile
index 59c42e1..625e5af 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -31,7 +31,7 @@ RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases
 #########################################
 # Set correct environment variables
 ENV CRASHPLAN_VERSION=4.8.0 \
-    CRASHPLAN_SERVICE=HOME  \
+    CRASHPLAN_SERVICE=PRO   \
     LC_ALL=en_US.UTF-8      \
     LANG=en_US.UTF-8        \
     LANGUAGE=en_US.UTF-8
```

A better way would be to allow passing it in as a `--build-arg`, but I will leave that up to the maintainer, as I am using Backblaze b2 instead of Crashplan these days.
