### ISSUE TITLE
Changing /proc/sys/fs/inotify/max_user_watches

### ISSUE THREAD

**Issue by last-Programmer** [JrCs/docker-crashplan#24]
Thank you for the container.

When i try to do this
https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_Real-Time_File_Watching_Errors
It says read only file system.

Is there a way to fix this issue? because in the crashplan logs i am getting the error 
Unable to add watch for path

Thank You

**Comment by JrCs** [comment]
You need to increase the `fs.inotify.max_user_watches`parameter on the host. For example you can create a configuration file in `/etc/sysctl.d`. Example `/etc/sysctl.d/crashplan.conf` with content:

```
fs.inotify.max_user_watches = 1048576
```
