### ISSUE TITLE
Losing links

### ISSUE THREAD

**Issue by bphagan** [JrCs/docker-crashplan#26]
I created a new container using the latest image from docker.
This is the 4.8.0 version.
When I open the container, I see the symlinks for the conf, cache, lib, log and land folders in /usr/local/crashplan/
Then within 10-20 minutes, Crashplan downloads an update (also 4.8.0) and restarts.
Now the symlinks for cache, lib and lang are gone and folders are now there.
The conf and log symlinks are still active.

Not sure why Crashplan is updating the same version.

Bdog

**Comment by bphagan** [comment]
Here is some other info:
First is listing right after install.
Second is history log about 5 minutes later
Third is listing currently.

> bash-4.3# ls -al /usr/local/crashplan/
> total 8976
> drwxr-xr-x 11 root root    4096 Nov 11 00:57 .
> drwxr-xr-x  9 root root    4096 Nov 11 00:57 ..
> -rw-r--r--  1 root root       3 Nov 11 00:57 CrashPlanEngine.pid
> -rw-rw-r--  1 root root 7639158 Oct  4 05:53 app.asar
> drwxrwxr-x  2 root root    4096 Nov 11 00:57 bin
> lrwxrwxrwx  1 root root      20 Nov 11 00:57 cache -> /var/crashplan/cache
> lrwxrwxrwx  1 root root      19 Nov 11 00:57 conf -> /var/crashplan/conf
> drwxrwxr-x  2 root root    4096 Oct  4 05:53 doc
> -rw-r--r--  1 root root     428 Oct  4 05:53 install.vars
> drwxr-xr-x  5 root root    4096 Oct  4 05:53 jre
> lrwxrwxrwx  1 root root      19 Nov 11 00:57 lang -> /var/crashplan/lang
> lrwxrwxrwx  1 root root      18 Nov 11 00:57 lib -> /var/crashplan/lib
> -rw-rw-r--  1 root root   11854 Oct  4 05:53 libc42archive.so
> -rw-rw-r--  1 root root   13060 Oct  4 05:53 libc42archive64.so
> -rw-rw-r--  1 root root   24756 Oct  4 05:53 libjniwrap.so
> -rw-rw-r--  1 root root   48344 Oct  4 05:53 libjniwrap64.so
> -rw-rw-r--  1 root root  257693 Oct  4 05:53 libjtux.so
> -rw-rw-r--  1 root root  287934 Oct  4 05:53 libjtux64.so
> -rw-rw-r--  1 root root  403970 Oct  4 05:53 libleveldb.so
> -rw-rw-r--  1 root root  427599 Oct  4 05:53 libleveldb64.so
> -rw-rw-r--  1 root root    7346 Oct  4 05:53 libmd5.so
> -rw-rw-r--  1 root root    8417 Oct  4 05:53 libmd564.so
> lrwxrwxrwx  1 root root      18 Nov 11 00:57 log -> /var/crashplan/log
> drwxrwxr-x  3 root root    4096 Oct  4 05:53 skin
> drwxrwxr-x  3 root root    4096 Oct  4 05:53 upgrade
> -rw-r--r--  1 root root       0 Nov 11 00:57 '~custom'
> bash-4.3#ls -al 
> 
> From history.log.0
> I 11/10/16 07:57PM CrashPlan started, version 4.8.0, GUID 768515842414485854
> I 11/10/16 07:57PM Backup scheduled to always run
> I 11/10/16 07:57PM Downloading a new version of CrashPlan.
> I 11/10/16 07:58PM Download of upgrade complete - version 1435813200480.
> I 11/10/16 07:58PM Installing upgrade - version 1435813200480
> I 11/10/16 07:58PM Upgrade installed - version 1435813200480
> I 11/10/16 07:58PM CrashPlan started, version 4.8.0, GUID 768515842414485854
> I 11/10/16 07:58PM [DSM Backup] Scanning for files to back up
> I 11/10/16 07:58PM [DSM Backup] Scanning for files completed in < 1 minute: 0 files (0MB) found
> I 11/10/16 07:58PM Backup scheduled to always run
> 
> bash-4.3# ls -al /usr/local/crashplan/
> total 54972
> drwxr-xr-x 17 root root     4096 Nov 11 00:58 .
> drwxr-xr-x  9 root root     4096 Nov 11 00:57 ..
> -rw-r--r--  1 root root        4 Nov 11 00:58 CrashPlanEngine.pid
> -rw-rw-r--  1 root root  7639158 Nov 11 00:58 app.asar
> drwxrwxr-x  2 root root     4096 Nov 11 00:58 bin
> drwxr-xr-x  2 root root     4096 Nov 11 00:58 cache
> lrwxrwxrwx  1 root root       19 Nov 11 00:57 conf -> /var/crashplan/conf
> drwxrwxr-x  2 root root     4096 Nov 11 00:58 doc
> -rw-r--r--  1 root root      459 Nov 11 00:58 install.vars
> drwxr-xr-x  5 root root     4096 Oct  4 05:53 jre
> drwxrwxr-x  2 root root     4096 Nov 11 00:58 lang
> drwxrwxr-x  2 root root     4096 Nov 11 00:58 lib
> -rw-rw-r--  1 root root    11854 Nov 11 00:58 libc42archive.so
> -rw-rw-r--  1 root root    13060 Nov 11 00:58 libc42archive64.so
> -rw-rw-r--  1 root root    24756 Nov 11 00:58 libjniwrap.so
> -rw-rw-r--  1 root root    48344 Nov 11 00:58 libjniwrap64.so
> -rw-rw-r--  1 root root   257693 Nov 11 00:58 libjtux.so
> -rw-rw-r--  1 root root   287934 Nov 11 00:58 libjtux64.so
> -rw-rw-r--  1 root root   403970 Nov 11 00:58 libleveldb.so
> -rw-rw-r--  1 root root   427599 Nov 11 00:58 libleveldb64.so
> -rw-rw-r--  1 root root     7346 Nov 11 00:58 libmd5.so
> -rw-rw-r--  1 root root     8417 Nov 11 00:58 libmd564.so
> lrwxrwxrwx  1 root root       18 Nov 11 00:57 log -> /var/crashplan/log
> drwxrwxr-x  4 root root     4096 Nov 11 00:58 skin
> drwxrwxr-x  3 root root     4096 Nov 11 00:58 upgrade
> -rw-r--r--  1 root root 47086963 Nov 11 00:58 upgrade.cpi
> -rw-r--r--  1 root root        0 Nov 11 00:58 '~custom'
> bash-4.3#

**Comment by JrCs** [comment]
Can you try the `dev`version ?
PS: backup the `id` directory in case of error.

**Comment by bphagan** [comment]
I would be happy to but not sure how to use the dev version.
I currently use sudo docker pull jrcs/crashplan to get the image.
I then use the docker run command to create the container.

Is there steps on how to use the dev version?

**Comment by JrCs** [comment]
Only use 

``` bash
docker pull jrcs/crashplan:dev
```

**Comment by JrCs** [comment]
Is it working now ?

**Comment by JrCs** [comment]
Closing issue. No more informations
