### ISSUE TITLE
Upgrade to CrashPlan 4.8 and QNAP NAS

### ISSUE THREAD

**Issue by mower7** [JrCs/docker-crashplan#27]
I'm not sure what changed, if it was something to do with the update to 4.8 or if it was a difference in the default docker settings in the QNAP setup.  But I needed to add --net=host to the command line.

The error I was seeing was that I could get the Crashplan server up and running, but no one could find it.  And the QNAP docker was making it an internal address by default.  Changing it to --net=host made the internal address reported by Crashplan into the real address of the NAS and then it was able to open up a uPnP port in my router.

This is very likely a specific to how the QNAP does its internal networking.

**Comment by noaho** [comment]
I noticed this on older versions too, if I wanted to communicate with PCs on my LAN it needed to be net=host. I can't remember if WAN destinations worked, maybe only crashplan central?

**Comment by mower7** [comment]
Yea, I wasn't sure if I figured out I needed it in a previous version too.  But I spent enough time banging my head trying to reinstall the container that I would mention it here just trying to save someone else the headache :)

(And this crashplan node went down about 2 weeks ago for unknown reasons, but it looked like it was having a hard time getting trough an upgrade cycle.. (seemed like it wanted someone to connect a client to it to finish the upgrade ?))  Then I decided to just redo the container and started banging my head :)

**Comment by JrCs** [comment]
Have you try to use the PUBLIC_IP and PUBLIC_PORT environment variables ?

**Comment by kkopachev** [comment]
Providing these does not work. It can't start listening on host IPs when network interface inside container has different ip range.
> [12.02.16 21:56:09.515 WARN  main         up42.service.peer.PeerController] Failed to start peer on 192.168.88.225. Reverting address to 0.0.0.0:4242
[12.02.16 21:56:09.517 INFO  main         .code42.messaging.peer.PeerGroup] PG::DefaultGroup cancelListen() location=[704633126896818401@192.168.88.225:4242]
[12.02.16 21:56:09.919 INFO  main         up42.service.peer.PeerController] STOP listening on 192.168.88.225:4242

192.168.88.0/24 is LAN. After all it listens on 0.0.0.0:4242, but client in the same LAN is trying to connect to 10.0.3.3:4242 (interface ip inside the container)

**Comment by kkopachev** [comment]
However, there is a workaround. If computer with backup to store on NAS has being connected previously to NAS, CrashPlan inside container can connect back to the client. In order to do that, client machine has to enable incoming backups in settings.
