### ISSUE TITLE
Accessing Crashplan GUI

### ISSUE THREAD

**Issue by sveinse** [JrCs/docker-crashplan#34]
With respect to #19, I agree with keeping the container lightweight. However (and unfortunately) GUI management is required in Crashplan, but I'd strongly want to avoid having it installed on my host server and on my desktop machine just for remote control. So how can we remotely access the GUI within the container?

One approach I wanted to try was to share the X session with the host and try to run CrashPlanDesktop from within the container. It requires some rude hacks, but this can be streamlined later if need be. What I did was:

## 1. Dockerfile

Patch the Dockerfile to get the missing libraries needed for X, adding `gtkx+2.0 libxtst` (line 9). I also added `xset` to verify that X is indeed working.

Now the dodgy part: A user account has to be created in the container which use the same UID and GID as the user trying to use X from. (Borrowed from here: http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/). I implemented this using:

<pre>
RUN export uid=1000 gid=1000 && \
   mkdir -p /home/user && \
   echo "user:x:${uid}:${gid}:User,,,:/home/user:/bin/ash" >> /etc/passwd && \
   echo "user:x:${uid}:" >> /etc/group && \
   chown ${uid}:${gid} -R /home/user
</pre>

In a more permanent setup, I'd propose setting this up dynamically from the install or entrypoint-script when creating the container.

## 2. Create the container

When creating the container, add the following statements to `docker run`:

<pre>
-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix
</pre>

(Its possible  `-v /tmp/.X11-unix:/tmp/.X11-unix:ro` can be used for better protection, but I didn't try it myself)

## 3. Run the desktop GUI

The default `/var/crashplan/app/bin/CrashPlanDesktop` script runs the main GUI using `&`, which does not  play well with `docker exec`, so it needs to be modified. Copy the script e.g. to `/var/crashplan/app/bin/cpd` and edit the file by removing the `&` (and perhaps the `>` redirects as well if you want to see the output):

<pre>
line 16:  ${JAVACOMMON} ${GUI_JAVA_OPTS} -classpath "./lib/com.backup42.desktop.jar:./lang:./skin" com.backup42.desktop.CPDesktop
</pre>

It can now be started from the host using:

<pre>
docker exec -it -u user crashplan /var/crashplan/app/bin/cpd
</pre>

..and then the experiment stops for me as the app crashes due to SEGFAULT. See below. I don't really know how to proceed. Maybe there are more X libs missing? A quick Google search gave me something (http://stackoverflow.com/questions/30491839/pthread-library-fails-when-called-from-static-constructor-code) about the glibc version being used, but I have no clue if this is a similar case.

<pre>
*************************************************************
*************************************************************
STARTED CrashPlanDesktop
CPVERSION = 4.8.0 - 1435813200480 (2015-07-02T05:00:00:480+0000) - Build: 331
ARGS      = []
LOCALE    = English (United States)
JVM       = Java(TM) SE Runtime Environment (1.8.0_72-b15, 64-bit)
OS        = Linux (4.4.0-53-generic, amd64)
User      = user, /home/user
swt.library.path = /tmp/.cpswt
*************************************************************
SWT library deleted: /tmp/.cpswt/libswt-pi-gtk-4427.so
SWT library deleted: /tmp/.cpswt/libswt-gtk-4427.so
Found and loading lib/org.eclipse.swt.gtk.linux.x86_64.jar
[file:/var/crashplan/app/lib/com.backup42.desktop.jar, file:/var/crashplan/app/lang/, file:/var/crashplan/app/skin/, file:/var/crashplan/app/lib/org.eclipse.swt.gtk.linux.x86_64.jar]
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_cond_init': Invalid argument.  Aborting.
/var/crashplan/app/bin/cpd: line 17:   336 Aborted                 (core dumped) ${JAVACOMMON} ${GUI_JAVA_OPTS} -classpath "./lib/com.backup42.desktop.jar:./lang:./skin" com.backup42.desktop.CPDesktop
</pre>

Anyhow, I hoped this little rundown could spawn some interest, and possibly how to figure out why the desktop GUI crashes.

**Comment by hutchic** [comment]
why not just access the GUI the way the README suggests? https://github.com/JrCs/docker-crashplan#access-the-gui-from-your-desktop-crashplan-application

or per CrashPlan website itself about how to use [headless crashplan](https://support.code42.com/CrashPlan/4/Configuring/Using_CrashPlan_On_A_Headless_Computer)

**Comment by sveinse** [comment]
Because both of them requires a local installation of CrashPlan as well as the container. The whole idea of having the docker container running CrashPlan is to isolate it from the host it runs on. I wanted to move my host CrashPlan server into the container to, well, contain it. It defeats the idea to have to install CrashPlan on the host for the GUI when you already have a perfectly good installation for it in the docker container. Having it both places kind of making the move into docker moot.

**Comment by hutchic** [comment]
you can install the CrashPlan GUI on a different host and connect over SSH.

To each their own if this is something you need I'd say go ahead and fork / pr :+1:

**Comment by sveinse** [comment]
I have to say I'm a little disappointed, but I'll respect this of course. I had hoped that this would spawn some interest, spending time preparing the case and all. I know too little about X and java-debugging to get any further on my own.

Since I can't run the GUI from this container, then I'm not going to use this container anyways. It makes no sense having CrashPlan in a container when you need the same CrashPlan installation on the server host to access the GUI. And I don't want to install CrashPlan on any other machines since I cannot ask of users to have to manually edit the .ui_info file.

Over and out.

**Comment by hutchic** [comment]
> you need the same CrashPlan installation on the server host to access the GUI

already explained you don't need it on the server host see previous link :)
