### ISSUE TITLE
Allow configuration of /proc/sys/fs/inotify/max_user_watches

### ISSUE THREAD

**Issue by haysclark** [JrCs/docker-crashplan#36]
I see the [60-max-user-watches.conf](https://github.com/JrCs/docker-crashplan/blob/master/files/60-max-user-watches.conf) file; however, it does not seem to be referenced by the other scripts or DOCKERFILE. __max_user_watches__ currently is defaulting to __8192__.

    bash-4.3# cat /proc/sys/fs/inotify/max_user_watches
    8192
    bash-4.3# echo 1048576 > /proc/sys/fs/inotify/max_user_watches
    bash: /proc/sys/fs/inotify/max_user_watches: Read-only file system

I was curious why my logs are filled with ```ode42.jna.inotify.InotifyManager] Unable to add watch for path``` messages. Then I found the Code42 [article](https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_Real-Time_File_Watching_Errors) about the error.  Maybe it's not possible to set via configuration due to Docker limitations?

**Comment by JrCs** [comment]
hi @haysclark,

Yes the  `60-max-user-watches.conf` is not use.
You need to change the value of /proc/sys/fs/inotify/max_user_watches from the host.
For example put the `60-max-user-watches.conf` into the /etc/sysctl.d directory of the host.
