### ISSUE TITLE
Runs Into 8k Limit on inotify user watches

### ISSUE THREAD

**Issue by adardia** [JrCs/docker-crashplan#37]
I've seen in my container instance's logs that the real-time monitoring engine has issues as its running into the limit of 8192 directory inotify user watches.  Crashplan's website has guidance [1] on this matter and gives a recommendation for how to adjust /etc/sysctl.conf.  However, when I try to do this on a bash shell opened on the container; it fails as below:

```
bash-4.3# cat /etc/sysctl.conf
# content of this file will override /etc/sysctl.d/*
fs.inotify.max_user_watches=1048576
bash-4.3# sysctl -p /etc/sysctl.conf
sysctl: setting key "fs.inotify.max_user_watches": error code 30
bash-4.3#
```

[This](https://github.com/docker/docker/issues/5703) 'docker' github issue highlights some questions around this with a suggestion that this needs to be solved at containers build-time.  Can we make this an argument to the container somehow?

[1] https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_Real-Time_File_Watching_Errors

**Comment by adardia** [comment]
For now, I've solved this by going onto the host itself, and applying it for the entire Synology NAS; but it'd be great to make this a container-specific setting.  But [Docker itself](https://docs.docker.com/engine/reference/commandline/run/#/configure-namespaced-kernel-parameters-sysctls-at-runtime) doesn't seem to expose fs.inotify.* as sysctl tunable settings.

**Comment by JrCs** [comment]
Yes it can only apply on the host.
