### ISSUE TITLE
No .ui-info file in conf folder?

### ISSUE THREAD

**Issue by mweinhauer** [JrCs/docker-crashplan#38]
Hi everyone - can't figure out what I'm doing wrong here, but this container seems to set up and run fine in Container Station, and Crashplan seems to be running. However I don't see a .ui_info file in the conf/id folder or anywhere in the conf folder, so I can't copy the token to my desktop and get this going.  Please help - thanks!

**Comment by grasshide** [comment]
Same problem here. I used this version: https://www.crashplan.com/en-us/download/

**Comment by JrCs** [comment]
the .ui_info file is in the **id** directory not in conf directory.
If you run docker with volume mount option like:
 -v /srv/crashplan/data:/var/crashplan
the .ui_info file is in /srv/crashplan/data/id

**Comment by mweinhauer** [comment]
Hi JrCs - That's what I wrote in my original post - it's not in the "conf/id" directory, so I don't see this issue as resolved.  I can't find the folder you suggest here nor the file either, and I've run a search on the entire file system.  I run my container as "docker run -d --name crashplan -e TZ=Etc/GMT+8 --publish 4242-4243:4242-4243 --volume /share/CACHEDEV1_DATA/Containers/CrashPlan:/var/crashplan --volume /share/CACHEDEV1_DATA:/storage jrcs/crashplan"

**Comment by JrCs** [comment]
@mweinhauer if you use the latest version of this container and if it's working well, your .ui_info file must be in /share/CACHEDEV1_DATA/Containers/CrashPlan/id/.ui_info

**Comment by mweinhauer** [comment]
Hi Yves – Thanks. The container runs and CrashPlan appears to be running, so I agree somewhere there must be a .ui_info, but it’s not there. I was thinking it was either somewhere else or through some permissions glitch or something I just couldn’t see it, but I did a full search and came up empty so it’s not the former.  I’m at a loss.  Thanks for validating what “should” be the case – I’ll continue to investigate and try other options. - Mike

**Comment by mweinhauer** [comment]
I found it! It's hidden by default, so you have to unhide it.  I used WinSCP and set the preferences to show hidden files and voila, there it is.  Would love to know how to see those using the CLI - still a Linux noob.
Grasshide hope this helps you out. OR you can just choose the preferences on your file station and check "show hidden files on NAS".  Damn wish I had seen this like a week ago!

**Comment by noaho** [comment]
ls -a to show all files (including hidden) on cli :)

**Comment by mweinhauer** [comment]
It's running now - works like a charm. My selected folders are all misaligned though - the UI says "missing".  I'll try mapping them to "/storage/..." instead of "/CACHEDEV1_DATA" since they seem to be dupes/symbolic links and maybe that will fix that issue.  I don't want to re-back up 3.2TB of data - that took 3 months the first time.

**Comment by noaho** [comment]
Make sure you don't unselect the originals in crashplan before you complete a backup of the new location. If you just add the new location the data dedupe system will just work out the new files are the same as before.. but if you unselect the old location (even missing) it deletes them immediately.

**Comment by mweinhauer** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Roger that - I didn't deselect - totally get that! Thanks!


Sent from Yahoo Mail for iPhone


On Thursday, March 2, 2017, 5:12 PM, NoahO <notifications@github.com> wrote:


Make sure you don't unselect the originals in crashplan before you complete a backup of the new location. If you just add the new location the data dedupe system will just work out the new files are the same as before.. but if you unselect the old location (even missing) it deletes them immediately.
