### ISSUE TITLE
File structure of folders to be backed up is different from QPKG and I can't get them to align

### ISSUE THREAD

**Issue by mweinhauer** [JrCs/docker-crashplan#39]
Hi there - I used to use the qpkg but that broke w 4.3 beta so I'm trying to make the container work. I have it running but the to be backed up directory mapping isn't aligned, so the console says "missing" for all my previously mapped (and backed up) directories.  I've tried configuring the variable to /, /share and share/CACHEDEV1_DATA but no dice.  It's 3TB of data so I'm not excited about scrapping the old backup and starting over.  Attached is a picture.  The checked boxes are what it's expecting, the one I see is "storage" that's actually expandable and selectable. If I deselect any of the existing ones they will be deleted from the backup.  Thanks for any help!
![crashplan file selection discrepancy](https://cloud.githubusercontent.com/assets/12705274/23582637/b6bad820-00e3-11e7-8739-d5e0ac3643aa.PNG)

**Comment by mweinhauer** [comment]
Oh and if I can change this config somehow without having to blow away the container and reinstantiate it please advise.  Container Station won't let me change it and I'd rather not have to redo the key copy steps if possible.  Thanks!

**Comment by mweinhauer** [comment]
Anyone - any ideas? Pretty please with sugar? ;-)

**Comment by kkopachev** [comment]
did you try starting container with mount like this:
```
--volume /share/CACHEDEV1_DATA:/share/CACHEDEV1_DATA
```
Not sure if it's going to work, though.

**Comment by mweinhauer** [comment]
I didn't - thought about it but assumed that the variable it was expecting was "storage" but I'll give it a shot now that you corroborated my thinking.  Thanks!

**Comment by mweinhauer** [comment]
Doesn't work - it sets that /storage variable anyway.  You're on the right track though I think - if I can figure out where/how that's set if it can be made to mirror the old structure it will work like a champ.  Thanks for the suggestion though!

**Comment by mweinhauer** [comment]
I stand corrected - it totally worked!!! YES! You are the man.  Thank you!!!
