### ISSUE TITLE
inbound backup not working

### ISSUE THREAD

**Issue by RangerRick** [JrCs/docker-crashplan#41]
My other crashplan clients on the internal network can't find the dockerized crashplan.  I suspect it's because the inbound local-network address is the container's 172.x.x.x address.  Do you have any ideas on how to make this work?

I'm not familiar enough  with docker to know if it's possible to bridge it, and it doesn't seem possible to change the internal address without attempting to "bind" to an address that doesn't exist from the container's POV.

**Comment by JrCs** [comment]
You can use your public ip to connect all the computers.
See: https://github.com/JrCs/docker-crashplan#optional-environment-variables

**Comment by RangerRick** [comment]
The public IP is already being reported correctly by CrashPlan.  My other internal CrashPlan clients just can't connect to it because my ISP's gateway doesn't allow looping back on itself (NAT loopback).
