### ISSUE TITLE
Document the meaning of the TZ environment variable

### ISSUE THREAD

**Issue by hheimbuerger** [JrCs/docker-crashplan#5]
The README suggests to pass the `TZ` environment variable from the host into the container. Please document the meaning and use of this variable.

Is it relevant to CrashPlan? I didn't find any information on the CrashPlan Linux client requiring it to be set. Or does something else in the container need it?

My docker host doesn't have this variable set by default. What should it be set to? The timezone I want to see in logs (probably UTC)? The actual timezone the server is in (why?)? The timezone I want to see in the UI when I connect it?

**Comment by JrCs** [comment]
TZ is used to set the timezone for the crashplan logs.
If it not set on the host the logs will be in UTC.

**Comment by JrCs** [comment]
Close 3c8b2c0
