### ISSUE TITLE
Changing PUBLIC_IP doesn't work

### ISSUE THREAD

**Issue by PArns** [JrCs/docker-crashplan#9]
I'm trying to reenable local backups by changing the env PUBLIC_IP and PUBLIC_PORT to 192.168.1.250/4242 but the container refuses to use that IP, the client still uses 0.0.0.0

Do I have to rebuild the container? (and if I need to do so, how?)

THX

**Comment by JrCs** [comment]
The PUBLIC_IP and PUBLIC_PORT are used to declare PUBLIC address (that can be access from internet). They are used to "FORCE" external ip/port when using NAT.
And you must also expose the ip/port for the container.
So for your docker run command do something like:

``` bash
export PUBLIC_IP=<ip>
export PUBLIC_PORT=<port> 
/usr/bin/docker run --rm \
    -e TZ \
    -e PUBLIC_IP -e PUBLIC_PORT \
    -p ${PUBLIC_IP}:${PUBLIC_PORT}:4242 \
    ... \
    jrcs/crashplan:latest
```
